---
- hosts: workstation
  post_tasks:
    - name: "[Bash] 'Hello World' script from files/hello_world.sh that simply echo 'Hello World (input: <all input>)' as output"
      script: hello_world.sh "Your Name" "Age 21" "Dog named Alice" etc..
      register: result
    - debug: var=result

  roles:
    - { role: common }

  tasks:
    - name: "[Python] 'Hello World' module from library/hello_world.py that simply returns 'Hello World' as output"
      hello_world:
      register: result
    - debug: var=result

  pre_tasks:
    - name: "[Python] 'Pass Variables' module from library/pass_variables.py that gets input, changes it and outputs new values"
      pass_variables:
        no_to_increment: 111
        name_to_change: Barbara
        description: "This input will be not modified"
      register: result
    - debug: var=result

- hosts: staging_group
  roles:
   - { role: common }

- hosts: production_group
  roles:
   - { role: common }

    
